### ISSUE TITLE
Two license files present

### ISSUE THREAD

**Issue by JokinSB** [SLiCAP/SLiCAP_python#1]
There are two license files in the repo:
- LICENSE, committed by @SpaceDreams containing the GNÇU LGPLv2.1.
- LICENCE.txt, committed by @waikikichocolates containing a link to the Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License.

For previous versions of the software, the second one (CC A-NC-ND v4.0) was included.

Which one to use could be a good discussion topic, but this ought to be done promptly, to solve this licensing conflict sooner than later.

**Comment by SpaceDreams** [comment]
Thanks for noticing that; the correct license is now the only license.
